### PR TITLE
WIP Initial commit

### PR DESCRIPTION
**Pull request by francescopellegrini**
### Please review

I cloned the base project files from the `embedded-kafka` project, removed the useless parts and updated the README.

### CODE REVIEW

**Comment by NeQuissimus** [comment]
Can you enable Travis CI?

**Comment by francescopellegrini** [comment]
> Can you enable Travis CI?

Yes, but compilation will fail until we publish at least a snapshot artifact of the new `embedded-kafka` repo..

**Comment by francescopellegrini** [comment]
Looks like I cannot enable Travis CI if there is no configuration in the master branch (it's been added in this PR...): can I push master up to this commit so we can enable Travis CI?

@manub can you publish a snapshot version of the new `embedded-kafka` project so that this project can compile?

**Comment by francescopellegrini** [comment]
Closing this since I pushed to the master branch.

**Pull request closed without merging**
